# .forge-lock.hcl — DO NOT EDIT MANUALLY
# Generated by forge. Changes will be overwritten on sync.

blueprint {
  registry_url = "github.com/donaldgifford/forge-registry"
  name         = "go-cli"
  path         = "go/cli"
}

created_at    = "2026-08-20T10:12:30.46671Z"
last_synced   = "2026-08-20T10:12:30.46671Z"
forge_version = "0.8.1"

variables {
  git_provider = {
    host                   = "github.com"
    name                   = "github"
    org                    = "donaldgifford"
    renovate_config_prefix = "github"
  }
  go_version                  = "1.26.6"
  license                     = "Apache-2.0"
  project_component_lifecycle = "production"
  project_component_owner     = "donaldgifford"
  project_component_system    = "dev-tools"
  project_component_type      = "cli"
  project_description         = "A Go CLI for Keycloak resources"
  project_name                = "keycloak-cli"
  project_owner               = "donaldgifford"
}

default ".claude/settings.json" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:55c9690e6b9fb691a757945053cbea31d84a658afb6f983b68bc1685a18e0d65"
}

default ".docz.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:dbadd93546136b41d8bdcc5bbf14b34a8c4c6cc3298ac2283bfec1be24fb1da5"
}

default ".github/CODEOWNERS" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:666453f28d6c351868d33031fd710f5ebab775b7dab797694b23eb587e161a4a"
}

default ".github/actionlint.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:4116d94fbad5355f4422bd9db3d7f1ba28126cb017f1125f6e55af967dc5b7bb"
}

default ".github/labeler.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d3b1b43336e037755731eb3f11a1d61a066429ce87078a566a1db89f92031975"
}

default ".github/licenses-csv.tpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:181b0c267bcc0c99b7e448de827c3a9a6c65ac4e2755d2529b9985018929b2f7"
}

default ".github/workflows/changelog-regen.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:224de5161f409a9a621ba7c26af352cf7b204e7a6de4307b0150c9941db38b69"
}

default ".github/workflows/changelog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:364e27010334331c58e86fce64b94fdcbd8a22003e31765847017f07e468faf8"
}

default ".github/workflows/ci.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d2fd347e45e57293ca2cdac030766a1992a95df34145ac4a114e337a44b2bf4c"
}

default ".github/workflows/pr-labels.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:1789341a42632af6acb115ede669f0f215e3b6f2a19a44107e352c4a556be2bd"
}

default ".github/workflows/release.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:01346219b30cc4d4e9f578487c3ec59f4568a97a9b48cb45973fd8da33aa00ee"
}

default ".github/workflows/trufflehog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:64745d904a21ca7392b3bfb018e0dd936ee87b9a5251bce22b4ff3874665784b"
}

default ".gitignore" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:242501690e1bab6a43e3ce312cd4699e12914ff0ae9604232669ffdcee59652c"
}

default ".markdownlint.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:c109f82759d9451b3060f5e8e1cb07752aca359faea7bc6057e61dd7eb7f20b7"
}

default ".prettierrc.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:265dc1424b9b6aeb0edab3e6a0e60302b7595a3fa2feb0c4656458967b841d23"
}

default ".yamlfmt.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:731740b1cb919db6cb1c7e26caafc4902a5a0d8d16729ac698227192b40ae473"
}

default ".yamllint.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:20c467f321f609e0188c6318f9da781d08783ec1319dea3c1946494f126ae707"
}

default "CHANGELOG.md" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:b64a7868c1db77e87d899af1d46c8c12d19a8c39d0b3b9a43753f75c1a0718aa"
}

default "CONTRIBUTING.md.tmpl" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:b052c14afe04f5414fb216358da766bb05d1dd0a7101022ad3068b414580c15b"
}

default "README.md.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:230da55f7c5c210c4a8d0d43ed4895cf8f0bf7fdbfceeace3c229e0f20cabc29"
}

default "catalog-info.yaml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:7edb85a60971b3ad05c8f58e18cd3ccef6d5751fefea8bf0c8e0333013730924"
}

default "cliff.toml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:82243509ccd95d1f2577220fd96cb6e01732b65405c3adfa327c5fa7763c6249"
}

default "justfile.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:b4c975c06b6e5cf9a44edd00380af3904f9782393cf3e7e696f7e562aa048b32"
}

default "mise.toml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:d8b31e6847b991d972ef8d8618cf052ebecd287979ead6b1fb6583151d0a34a9"
}

default "renovate.json5.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:15f4007ddcaa61259c275a55d0587b73d610f7a7e1bab6351518c61c962e280a"
}

default "scripts/labels.sh" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:9a67e59fc7ea35194415b9ad246d14cc3296aa1a588d01a24ac7ea7784ecdcb3"
}

default ".codecov.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:b48d421520733589f478818e2bae21422999c4ce0b4fc82139c229bdae0c8114"
}

default ".github/dependabot.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:83ecabd7a4689bbef3cb8ba512f91c1ad2176a9121a0daab7a7adb4e6855f210"
}

default ".github/workflows/codeql.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:650ac701d9850da0bf781c197b2e7cfd0295d0eaf6414073ec8d6b5da073bf0e"
}

default ".github/workflows/dependabot-severity-label.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:331019181284ad68d156474cb7fd3ffe17453943d68b6e76df0f5c931481a6cc"
}

default ".github/workflows/license-check.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:fdbc23ba9b8bf9c962bfc492acd98806018d845c212534519c4a0ef81e8dad23"
}

default ".github/workflows/security.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:a8e9146925097d1c9b0049014c299c021a5dfab73322864a2019447f85500f38"
}

default ".gitignore.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:242501690e1bab6a43e3ce312cd4699e12914ff0ae9604232669ffdcee59652c"
}

default ".golangci.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:57d9bfb542912e3507eeff1431affe3b0e1e088f8ed69d4d4143f18dcf660dd5"
}

default ".goreleaser.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:75ec31ff7aea38298b29f7c0483a565dffdc29b5c2f242986b1eb9901cabf966"
}

default "CLAUDE.md.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d9b37fa97eccd6743e116b7ccc3446b899c298fe7c560745ead3acea035d1a66"
}

default "cmd/$${project_name}/main.go.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
}

default "go.mod.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:2dbbd22c082416166de7f9b15ee2133982f052506531c9a017f87d845f8a0b9e"
}

default "internal/.gitkeep" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
}
