---
# $schema=https://www.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: keycloak-cli
  title: keycloak-cli
  description: A Go CLI for Keycloak resources
  annotations:
    backstage.io/source-location: url:https://github.com/donaldgifford/keycloak-cli
    backstage.io/techdocs-ref: "dir:."
  tags:
    - go
  namespace: default
spec:
  lifecycle: production
  type: tool
  owner: donaldgifford
  system: dev-tools
